[package]
name = "datafusion_malloc_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
jemallocator = "0.5.0"
mimalloc = { version = "0.1.34", default-features = false }
